### ISSUE TITLE
.sandbox.token文件项目拉下来后没有找到

### ISSUE THREAD

**Issue by DrYaoHongBin** [JayeShen/Moonbox-k8s#1]
将moonbox启动所需文件和文件夹直接打包在docker镜像的中（必须是根目录），或者通过k8s的configmap挂载到容器中
具体包括:
文件夹：.sandbox-module/、、sandbox/，文件.sandbox.token

![image](https://github.com/JayeShen/Moonbox-k8s/assets/28960657/8b52f83a-36a7-45f1-b214-fd9f3eef6b63)

根据文档提示，只找到以上两个文件，项目拉下来后没有找到.sandbox.token这个文件，请问这个文件得在哪找到

**Comment by JayeShen** [comment]
正常本地电脑测试之后，会在本地根目录下生成
<img width="572" alt="image" src="https://github.com/JayeShen/Moonbox-k8s/assets/53166168/19e09f88-a83c-4554-bfb8-568b137ded91">
[
[解压.zip](https://github.com/JayeShen/Moonbox-k8s/files/15036509/default.zip)
](url)

**Comment by JayeShen** [comment]
我这个解压.zip帮你上传了
